##' Parse MCMC parameter names
##'
##' These functions parse a character vector of parameter names and
##' return a \code{McmcParnames} object.
##'
##' @param x \code{character} vector of character names.
##'
##' @return \code{McmcParnames} data.frame.
##'
##' @rdname mcmc_parse_parname
##' @export
mcmc_parse_parname_default <- function(x) {
    result <- data.frame(parname=as.factor(x),
                         pararray=as.factor(x),
                         idx=rep("1", length(x)),
                         stringsAsFactors=FALSE)
    rownames(result) <- x
    new("McmcParnames", result)
}

##' @rdname mcmc_parse_parname
##' @export
mcmc_parse_parname_stan <- function(x) {
    result <- data.frame(str_split_fixed(x, fixed("."), n=2))
    colnames(result) <- c("pararray", "idx")
    result$parname <- as.factor(x)
    rownames(result) <- x
    result$idx <- str_replace_all(result[ , 2], fixed("."), fixed(","))
    result$idx[result$idx == ""] <- "1"
    new("McmcParnames", result[ , c("parname", "pararray", "idx")])
}

##' @rdname mcmc_parse_parname
##' @export
mcmc_parse_parname_bugs <- function(x) {
    result <-
        data.frame(str_match(x, "([^\\[]+)(\\[([0-9,]+)\\])?")[ , c(2, 4)])
    colnames(result) <- c("pararray", "idx")
    result$idx <- as.character(result$idx)
    result$parname <- as.factor(x)
    rownames(result) <- x
    result$idx[result$idx == ""] <- "1"
    new("McmcParnames", result[ , c("parname", "pararray", "idx")])
}

## @param x McmcParnames objects
parnames_to_pararrays <- function(x) {
    f <- function(x) {
        indices <- x$idx
        dim_n <- str_count(indices[1], fixed(",")) + 1L
        dims <- matrix(as.integer(str_split_fixed(indices, fixed(","), dim_n)),
                       nrow(x), dim_n)
        dim_sz <- paste(apply(dims, 2, max), collapse=",")
        data.frame(dim_n = dim_n, dim_sz = dim_sz,
                   stringsAsFactors=FALSE)
    }
    new("McmcPararrays", strip_plyr_attr(ddply(x, "pararray", f)))
}

# Check if parameter names are consistent with those generated by BUGS
checkif_bugs_parameters <- function(x) {
    str_all_match(x, "^[A-Za-z.][A-Za-z.0-9]*(\\[\\d(,\\d)*\\])?$")
}

# Check if parameter names are consistent with those generated by Stan
# All Stan parameters are technically BUGS parameters
checkif_stan_parameters <- function(x) {
    str_all_match(x, "^[A-Za-z][A-Za-z0-9_]*(\\.\\d)*$")
}

##' Create Unlisted Parameter Names
##'
##' Given a parameter name and a matrix of index values, generate
##' names for the unlisted parameters.
##'
##' @param x \code{character}. Parameter name.
##' @param idx \code{matrix} of indices.
##'
##' @rdname mcmc_create_parnames
##' @export
mcmc_create_parnames_stan <- function(x, idx) {
    if (length(idx) == 1) {
        x
    } else {
        idxstr <- apply(idx, 1, paste, collapse=".")
        paste(x, idxstr, sep=".")
    }
}

##' @rdname mcmc_create_parnames
##' @export
mcmc_create_parnames_bugs <- function(x, idx) {
    if (length(idx) == 1) {
        x
    } else {
        idx <- as.matrix(idx)
        idxstr <- apply(idx, 1, paste, collapse=",")
        paste0(x, "[", idxstr, "]")
    }
}
