#' @include package.R
#' @export valid_mcmc_parnames
NULL

#' Check MCMC parameter names
#'
#' Check flat parameter names to see if they are consistent
#' with the parameter names generated by BUGS or Stan.
#'
#' @param x \code{character} vector of flat parameter names
#' @param style Eiter \code{"bugs"} or \code{"stan"}, to check
#' if the parameters are valid BUGS/JAGS or Stan names, respectively.
#' @return \code{logical} vector of same length as \code{x} with the validity of each
#' flat parameter name.
#' @rdname valid_mcmc_parnames
#' @examples
#' valid_mcmc_parnames("beta[1]")
#' valid_mcmc_parnames("beta[1]", "stan")
#' valid_mcmc_parnames("beta.1", "stan")
valid_bugs_name <- function(x, style="bugs") {
  
    as.logical(sapply(str_match_all(x, "^[A-Za-z.][A-Za-z.0-9]*(\\[\\d(,\\d)*\\])?$"), length))
  } else if (style == "stan") {
    as.logical(sapply(str_match_all(x, "^[A-Za-z][A-Za-z0-9_]*(\\.\\d)*$"), length))
  } else {
    stop("Option %s must be either %s or %s",
         sQuote("style"), dQuote("bugs"), dQuote("stan"))
  }
}

## List of C++ keywords from http://en.cppreference.com/w/cpp/keyword
CPP_RESERVED <-
    c('alignas', 'alignof', 'and', 'and_eq', 'asm', 'auto', 'bitand', 'bitor',
      'bool', 'break', 'case', 'catch', 'char', 'char16_t', 'char32_t', 'class',
      'compl', 'const', 'constexpr', 'const_cast', 'continue', 'decltype',
      'default', 'delete', 'do', 'double', 'dynamic_cast', 'else', 'enum',
      'explicit', 'export', 'extern', 'false', 'float', 'for', 'friend', 'goto',
      'if', 'inline', 'int', 'long', 'mutable', 'namespace', 'new', 'noexcept',
      'not', 'not_eq', 'nullptr', 'operator', 'or', 'or_eq', 'private', 'protected',
      'public', 'register', 'reinterpret_cast', 'return', 'short', 'signed',
      'sizeof', 'static', 'static_assert', 'static_cast', 'struct', 'switch',
      'template', 'this', 'thread_local', 'throw', 'true', 'try', 'typedef',
      'typeid', 'typename', 'union', 'unsigned', 'using', 'virtual', 'void',
      'volatile', 'wchar_t', 'while', 'xor', 'xor_eq', 'override', 'final')
## List of Stan reserved keywords
## See 16.2 of Stan Manual
STAN_RESERVED <-
    c('for', 'in', 'while', 'repeat', 'until', 'if', 'then', 'else',
      'true', 'false', 'int', 'real', 'vector', 'simplex', 'ordered',
      'row_vector', 'matrix', 'corr_matrix', 'cov_matrix')

##' Check validity of STAN parameter name
##'
##' @return A \code{logical} vector indicating whether the element is
##' a valid Stan variable name.
##'
##' A Stan variable must
##'
##' \itemize{
##' \item Start with \code{[A-Za-z]}
##' \item Contain only \code{[A-Za-z0-9_]}
##' \item Not conflict with C++ or Stan reserved keywords
##' \item Not end with \code{__}.
##' \item Not be a reserved word in Stan or C++
##' }
##'
##' @keywords internal
valid_stan_name <- function(x) {
    (grepl("^[A-Za-z][A-Za-z0-9_]*$", x)
     & !grepl("__$", x)
     & ! x %in% union(CPP_RESERVED, STAN_RESERVED))
}
