#' @include package.R
NULL

#' Check MCMC parameter names
#'
#' Check flat parameter names to see if they are consistent
#' with the parameter names generated by BUGS or Stan.
#'
#' @param x \code{character} vector of flat parameter names
#' @param style Eiter \code{"bugs"} or \code{"stan"}, to check
#' if the parameters are valid BUGS/JAGS or Stan names, respectively.
#' @return \code{logical} vector of same length as \code{x} with the validity of each
#' flat parameter name.
#' @rdname valid_mcmc_parnames
#' @export
#' @examples
#' valid_mcmc_parnames("beta[1]")
#' valid_mcmc_parnames("beta[1]", "stan")
#' valid_mcmc_parnames("beta.1", "stan")
valid_mcmc_parnames <- function(x, style="bugs") {
  if (style == "bugs") {
    as.logical(sapply(str_match_all(x, "^[A-Za-z.][A-Za-z.0-9]*(\\[\\d(,\\d)*\\])?$"), length))
  } else if (style == "stan") {
    as.logical(sapply(str_match_all(x, "^[A-Za-z][A-Za-z0-9_]*(\\.\\d)*$"), length))
  } else {
    stop("Option %s must be either %s or %s",
         sQuote("style"), dQuote("bugs"), dQuote("stan"))
  }
}
